const groceryData = [
  {
    id: "1",
    name: "Potato 500g",
    category: "Vegetables",
    price: 25,
    offerPrice: 20,
    count: "1",
    image: "/images/potato_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Fresh and organic",
      "Rich in carbohydrates",
      "Ideal for curries and fries",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "2",
    name: "Tomato 1 kg",
    category: "Vegetables",
    price: 40,
    offerPrice: 35,
    count: "1",
    image: "/images/tomato_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Juicy and ripe",
      "Rich in Vitamin C",
      "Perfect for salads and sauces",
      "Farm fresh quality",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "3",
    name: "Carrot 500g",
    category: "Vegetables",
    type:"breakfast",
    price: 30,
    offerPrice: 28,
    count: "1",
    image: "/images/carrot_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Sweet and crunchy",
      "Good for eyesight",
      "Ideal for juices and salads",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "4",
    name: "Spinach 500g",
    category: "Vegetables",
    price: 18,
    offerPrice: 15,
    count: "1",
    image: "/images/spinach_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Rich in iron",
      "High in vitamins",
      "Perfect for soups and salads",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "5",
    name: "Onion 500g",
    category: "Vegetables",
    price: 22,
    offerPrice: 19,
    count: "1",
    image: "/images/onion_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Fresh and pungent",
      "Perfect for cooking",
      "A kitchen staple",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Fruits
  {
    id: "6",
    name: "Apple 1 kg",
    category: "Fruits",
    type:"breakfast",
    price: 120,
    offerPrice: 110,
    count: "1",
    image: "/images/apple_image.png",
    ratings: "★★★★★",
    noratings: "",
    description: [
      "Crisp and juicy",
      "Rich in fiber",
      "Boosts immunity",
      "Perfect for snacking and desserts",
      "Organic and farm fresh",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "7",
    name: "Orange 1 kg",
    category: "Fruits",
    type:"breakfast",
    price: 80,
    offerPrice: 75,
    count: "1",
    image: "/images/orange_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Juicy and sweet",
      "Rich in Vitamin C",
      "Perfect for juices and salads",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "8",
    name: "Banana 1 kg",
    category: "Fruits",
    type:"breakfast",
    price: 50,
    offerPrice: 45,
    count: "1",
    image: "/images/banana_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Sweet and ripe",
      "High in potassium",
      "Great for smoothies and snacking",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "9",
    name: "Mango 1 kg",
    category: "Fruits",
    type:"breakfast",
    price: 150,
    offerPrice: 140,
    count: "1",
    image: "/images/mango_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Sweet and flavorful",
      "Perfect for smoothies and desserts",
      "Rich in Vitamin A",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "10",
    name: "Grapes 500g",
    category: "Fruits",
    type:"breakfast",
    price: 70,
    offerPrice: 65,
    count: "1",
    image: "/images/grapes_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Fresh and juicy",
      "Rich in antioxidants",
      "Perfect for snacking and fruit salads",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Dairy
  {
    id: "11",
    name: "Amul Milk 1L",
    category: "Dairy",
    type:"breakfast",
    price: 60,
    offerPrice: 55,
    count: "1",
    image: "/images/amul_milk_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Pure and fresh",
      "Rich in calcium",
      "Ideal for tea, coffee, and desserts",
      "Trusted brand quality",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "12",
    name: "Paneer 200g",
    category: "Dairy",
    type:"breakfast",
    price: 90,
    offerPrice: 85,
    count: "1",
    image: "/images/paneer_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Soft and fresh",
      "Rich in protein",
      "Ideal for curries and snacks",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "13",
    name: "Eggs 12 pcs",
    category: "Dairy",
    type:"breakfast",
    price: 90,
    offerPrice: 85,
    count: "1",
    image: "/images/eggs_image.png",
    ratings: "★★★★★",
    noratings: "",
    description: [
      "Farm fresh",
      "Rich in protein",
      "Ideal for breakfast and baking",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "14",
    name: "Cheese 200g",
    category: "Dairy",
    price: 140,
    offerPrice: 130,
    count: "1",
    image: "/images/cheese_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Creamy and delicious",
      "Perfect for pizzas and sandwiches",
      "Rich in calcium",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Drinks
  {
    id: "15",
    name: "Coca-Cola 1.5L",
    category: "Drinks",
    price: 80,
    offerPrice: 75,
    count: "1",
    image: "/images/coca_cola_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Refreshing and fizzy",
      "Perfect for parties and gatherings",
      "Best served chilled",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "16",
    name: "Pepsi 1.5L",
    category: "Drinks",
    price: 78,
    offerPrice: 73,
    count: "1",
    image: "/images/pepsi_image.png",
    ratings: "★★",
    noratings: "★★★",
    description: [
      "Chilled and refreshing",
      "Perfect for celebrations",
      "Best served cold",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "17",
    name: "Sprite 1.5L",
    category: "Drinks",
    price: 79,
    offerPrice: 74,
    count: "1",
    image: "/images/sprite_image_1.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Refreshing citrus taste",
      "Perfect for hot days",
      "Best served chilled",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "18",
    name: "Fanta 1.5L",
    category: "Drinks",
    price: 77,
    offerPrice: 72,
    count: "1",
    image: "/images/fanta_image_1.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Sweet and fizzy",
      "Great for parties and gatherings",
      "Best served cold",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "19",
    name: "7 Up 1.5L",
    category: "Drinks",
    price: 76,
    offerPrice: 71,
    count: "1",
    image: "/images/seven_up_image_1.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Refreshing lemon-lime flavor",
      "Perfect for refreshing",
      "Best served chilled",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Grains
  {
    id: "20",
    name: "Basmati Rice 5kg",
    category: "Grains",
    price: 550,
    offerPrice: 520,
    count: "1",
    image: "/images/basmati_rice_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Long grain and aromatic",
      "Perfect for biryani and pulao",
      "Premium quality",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "21",
    name: "Wheat Flour 5kg",
    category: "Grains",
    price: 250,
    offerPrice: 230,
    count: "1",
    image: "/images/wheat_flour_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "High-quality whole wheat",
      "Soft and fluffy rotis",
      "Rich in nutrients",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "22",
    name: "Organic Quinoa 500g",
    category: "Grains",
    price: 450,
    offerPrice: 420,
    count: "1",
    image: "/images/quinoa_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "High in protein and fiber",
      "Gluten-free",
      "Rich in vitamins and minerals",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "23",
    name: "Brown Rice 1kg",
    category: "Grains",
    price: 120,
    offerPrice: 110,
    count: "1",
    image: "/images/brown_rice_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Whole grain and nutritious",
      "Helps in weight management",
      "Good source of magnesium",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "24",
    name: "Barley 1kg",
    category: "Grains",
    price: 150,
    offerPrice: 140,
    count: "1",
    image: "/images/bakery_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Rich in fiber",
      "Helps improve digestion",
      "Low in fat and cholesterol",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Bakery
  {
    id: "25",
    name: "Brown Bread 400g",
    category: "Bakery",
    type:"breakfast",
    price: 40,
    offerPrice: 35,
    count: "1",
    image: "/images/brown_bread_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Soft and healthy",
      "Made from whole wheat",
      "Ideal for breakfast and sandwiches",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "26",
    name: "Butter Croissant 100g",
    category: "Bakery",
    type:"breakfast",
    price: 50,
    offerPrice: 45,
    count: "1",
    image: "/images/butter_croissant_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Flaky and buttery",
      "Freshly baked",
      "Perfect for breakfast or snacks",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "27",
    name: "Chocolate Cake 500g",
    category: "Bakery",
    type:"breakfast",
    price: 350,
    offerPrice: 325,
    count: "1",
    image: "/images/chocolate_cake_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Rich and moist",
      "Made with premium cocoa",
      "Ideal for celebrations and parties",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "28",
    name: "Whole Bread 400g",
    category: "Bakery",
    type:"breakfast",
    price: 45,
    offerPrice: 40,
    count: "1",
    image: "/images/whole_wheat_bread_image.png",
    ratings: "★★",
    noratings: "★★★",
    description: [
      "Healthy and nutritious",
      "Made with whole wheat flour",
      "Ideal for sandwiches and toast",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "29",
    name: "Vanilla Muffins 6 pcs",
    category: "Bakery",
    type:"breakfast",
    price: 100,
    offerPrice: 90,
    count: "1",
    image: "/images/vanilla_muffins_image.png",
    ratings: "★★",
    noratings: "★★★",
    description: [
      "Soft and fluffy",
      "Perfect for a quick snack",
      "Made with real vanilla",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Instant
  {
    id: "30",
    name: "Maggi Noodles 280g",
    category: "Instant",

    price: 55,
    offerPrice: 50,
    count: "1",
    image: "/images/maggi_image.png",
    ratings: "★★",
    noratings: "★★★",
    description: [
      "Instant and easy to cook",
      "Delicious taste",
      "Popular among kids and adults",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "31",
    name: "Top Ramen 270g",
    category: "Instant",
    price: 45,
    offerPrice: 40,
    count: "1",
    image: "/images/top_ramen_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Quick and easy to prepare",
      "Spicy and flavorful",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "32",
    name: "Yippee Noodles 260g",
    category: "Instant",
    price: 50,
    offerPrice: 45,
    count: "1",
    image: "/images/yippee_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Non-fried noodles for healthier choice",
      "Tasty and filling",
      "Convenient for busy schedules",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "33",
    name: "Oats Noodles 72g",
    category: "Instant",
    price: 40,
    offerPrice: 35,
    count: "1",
    image: "/images/maggi_oats_image.png",
    ratings: "★★★★★",
    noratings: "",
    description: [
      "Healthy alternative with oats",
      "Good for digestion",
      "Perfect for breakfast or snacks",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  //FastFood

  {
    id: "34",
    name: "Chicken Burger",
    category: "FastFood",
    price: 99,
    offerPrice: 89,
    count: "1",
    image: "/images/chicken Burger.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Tasty & delicious",
      "Perfect for snacks",
      "Popular among kids and adults",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  // {
  //   id: "35",
  //   name: "Chicken Kabab",
  //   category: "FastFood",
  //   price: 80,
  //   offerPrice: 70,
  //   image: "/images/chicken kabab.png",
  //   ratings: "★★",
  //   noratings: "★★★",
  //   description: [
  //     "Tasty & delicious",
  //     "Perfect for snacks",
  //     "Popular among kids and adults",
  //   ],
  //   createdAt: "2025-03-25T07:17:46.018Z",
  //   updatedAt: "2025-03-25T07:18:13.103Z",
  //   inStock: true,
  // },
  {
    id: "36",
    name: "Chicken Leg Peace",
    category: "FastFood",
    price: 150,
    offerPrice: 120,
    count: "1",
    image: "/images/chicken leg peace.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Tasty & delicious",
      "Perfect for snacks",
      "Popular among kids and adults",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },

  // Ice Cream

  {
    id: "37",
    name: "Chocolate Cone Cream Isolated",
    category: "IceCream",
    price: 40,
    offerPrice: 35,
    count: "1",
    image: "/images/chocolate cone ice cream isolated.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "38",
    name: "Chocolate Sundae",
    category: "IceCream",
    price: 140,
    offerPrice: 135,
    count: "1",
    image: "/images/cream sundae.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "39",
    name: "Five Colorful Ice Cream Cones Isolated",
    category: "IceCream",
    price: 200,
    offerPrice: 185,
    count: "1",
    image: "/images/five colorful ice cream cones isolated on white.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "40",
    name: "Ice Cream Cones With Chocolate Vanilla",
    category: "IceCream",
    price: 200,
    offerPrice: 185,
    count: "1",
    image: "/images/ice cream cones with chocolate vanilla.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "41",
    name: "Ice Cream Cones With Chocolate Vanilla",
    category: "IceCream",
    price: 99,
    offerPrice: 89,
    count: "1",
    image: "/images/ice cream cones with chocolate vanilla.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },


  {
    id: "42",
    name: "Chocolate cake",
    category: "Cake",
    price: 200,
    offerPrice: 180,
    count: "1",
    image: "/images/chocolate_cake_image.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },


{
    id: "43",
    name: "Sliced Pepperoni Pizza",
    category: "FastFood",
    price: 120,
    offerPrice: 100,
    count: "1",
    image: "/images/sliced pepperoni pizza.png",
    ratings: "★★★★",
    noratings: "★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "44",
    name: "Vanilla Muffins",
    category: "Cake",
    price: 80,
    offerPrice: 70,
    count: "1",
    image: "/images/vanilla_muffins_image.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
  {
    id: "45",
    name: "Chocolate Cookies",
    category: "Cake",
    price: 99,
    offerPrice: 89,
    count: "1",
    image: "/images/vecteezy_chocolate-cookies-isolated-on-a-transparent-background_46635353.png",
    ratings: "★★★",
    noratings: "★★",
    description: [
      "Tasty & Sweet",
      "Soft and fluffy",
      "Loved by college students and families",
    ],
    createdAt: "2025-03-25T07:17:46.018Z",
    updatedAt: "2025-03-25T07:18:13.103Z",
    inStock: true,
  },
]




export default groceryData;